config/routes.rb
Rails.application.routes.draw do
  resources :courses

  resources :semesters

  resources :campus

  resources :academic_units

  resources :teachers

end

app/models/academic_unit.rb
class AcademicUnit < ActiveRecord::Base
	validates :name, :presence => true, :uniqueness => true
end

app/controllers/academic_units_controller.rb
class AcademicUnitsController < ApplicationController
  before_action :set_academic_unit, only: [:show, :edit, :update, :destroy]

  # GET /academic_units
  # GET /academic_units.json
  def index
    @academic_units = AcademicUnit.all
  end

  # GET /academic_units/1
  # GET /academic_units/1.json
  def show
  end

  # GET /academic_units/new
  def new
    @academic_unit = AcademicUnit.new
  end

  # GET /academic_units/1/edit
  def edit
  end

  # POST /academic_units
  # POST /academic_units.json
  def create
    @academic_unit = AcademicUnit.new(academic_unit_params)

    respond_to do |format|
      if @academic_unit.save
        format.html { redirect_to @academic_unit, notice: 'Academic unit was successfully created.' }
        format.json { render :show, status: :created, location: @academic_unit }
      else
        format.html { render :new }
        format.json { render json: @academic_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /academic_units/1
  # PATCH/PUT /academic_units/1.json
  def update
    respond_to do |format|
      if @academic_unit.update(academic_unit_params)
        format.html { redirect_to @academic_unit, notice: 'Academic unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @academic_unit }
      else
        format.html { render :edit }
        format.json { render json: @academic_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /academic_units/1
  # DELETE /academic_units/1.json
  def destroy
    @academic_unit.destroy
    respond_to do |format|
      format.html { redirect_to academic_units_url, notice: 'Academic unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_academic_unit
      @academic_unit = AcademicUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def academic_unit_params
      params.require(:academic_unit).permit(:name)
    end
end

app/helpers/academic_units_helper.rb
module AcademicUnitsHelper
end

app/views/academic_units/_form.html.erb
<%= simple_form_for @academic_unit, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                academic_units_path, :class => 'btn' %>
  </div>
<% end %>

app/views/academic_units/edit.html.erb
<%- model_class = AcademicUnit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/academic_units/index.html.erb
<%- model_class = AcademicUnit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @academic_units.each do |academic_unit| %>
      <tr>
        <td><%= link_to academic_unit.id, academic_unit_path(academic_unit) %></td>
        <td><%= academic_unit.name %></td>
        <td><%=l academic_unit.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_academic_unit_path(academic_unit), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      academic_unit_path(academic_unit),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_academic_unit_path,
            :class => 'btn btn-primary' %>

app/views/academic_units/new.html.erb
<%- model_class = AcademicUnit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/academic_units/show.html.erb
<%- model_class = AcademicUnit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @academic_unit.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              academic_units_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_academic_unit_path(@academic_unit), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              academic_unit_path(@academic_unit),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>